# Ark sample commands

default:
    @just --list

# Show the balance for a given actor (e.g., alice, bob)
balance actor:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed balance

# Show the transaction history for a given actor
transaction-history actor:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed transaction-history

# Generate a boarding address for a given actor
boarding-address actor:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed boarding-address

# Generate an Ark address for a given actor
offchain-address actor:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed offchain-address

# Send coins to an Ark address from a given actor
send actor address amount:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed send-to-ark-address {{address}} {{amount}}

# Transform boarding outputs and VTXOs into fresh, confirmed VTXOs for a given actor
settle actor:
    cargo run -p ark-sample -- --config ./{{actor}}/ark.config.toml --seed ./{{actor}}/ark.seed settle
